### PR TITLE
Added wrf to both stacks

### PR DESCRIPTION
**Pull request by batatasfritas**
- MPI+OpenMP (build_type=dm+sm) since the performance justifies it
- Depends on https://github.com/epfl-scitas/scitas-spack-packages/pull/12 since original wrf recipe fails for 4.5

### CODE REVIEW

**Review by nrichart — CHANGES_REQUESTED** [review]
`wrf` depends on  `netcdf-c` and `parallel-netcdf` not necessarly `nettdf-c+parallel-netcdf`

should it be `wrf ^netcdf-fortran ^netcdf-c+mpi ^parallel-netcdf` to be sur to use the already installed netcdf-{c,fortran} ?

**Comment by batatasfritas** [comment]
I based this on what I needed to get this to compile, but I do agree a more complete description option is perhaps in order (so I'll modify to add `^netcdf-fortran ...`)
Before that I'll look further into the `+mpi` and `+parallel-netcdf` to see what makes the most sense here...

**Comment by nrichart** [comment]
My  guess is that `wrf` compilation system does not rpath so  we will need a module for `netcdf-c+parallel-netcdf` if it is the case we need to add a suffix in `module.yaml` to avoid the name clash

**Comment by batatasfritas** [comment]
No, it seems Spack does the right thing (even if wrf doesn't by default). On my old install:
```
grep SPACK_RPATH_DIRS spack-build-env.txt | grep -c parallel-netcdf
1
```
and looking at the `ldd` output everything seems to be correct.

**Review by batatasfritas — COMMENTED** [review]
The performance of:
`wrf ~pnetcdf ^netcdf-c +mpi ~parallel-netcdf ^netcdf-fortran`

is as good[1] as that of what I had originally suggested and it doesn't depend on parallel-netcdf.

Waiting for your approval, but this addresses your original concern and works around the issues we'd discussed, so it should be fine.

[1] - Tested for the type of job the user gave me, YMMV for other stuff. Tested on the bigmem nodes.

**Review by nrichart — APPROVED** [review]
LGTM

**Pull request merged**
